# -*- coding: utf-8 -*-
"""SKYLARK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eQzEvl5A-v9_fqzG520zr6VGetuSDI5C
"""

from google.colab import drive
drive.mount('/content/drive')

import os

dataset_path = "/content/drive/MyDrive/GCP_Assignment_Datasets"
train_path = dataset_path + "/content/drive/MyDrive/GCP_Assignment_Datasets/train_dataset"
test_path = dataset_path + "/content/drive/MyDrive/GCP_Assignment_Datasets/test_dataset"
label_path = "/content/drive/MyDrive/GCP_Assignment_Datasets/train_dataset/gcp_marks.json"

import os
os.listdir("/content/drive/MyDrive/GCP_Assignment_Datasets")

import os
import json
import cv2
import torch
import numpy as np
import matplotlib.pyplot as plt

from torch.utils.data import Dataset, DataLoader
import torchvision.transforms as transforms
import torchvision.models as models
import torch.nn as nn

with open(label_path) as f:
    labels = json.load(f)
print("Total labeled images:", len(labels))

import os
os.listdir("/content/drive/MyDrive/GCP_Assignment_Datasets")

os.listdir("/content/drive/MyDrive/GCP_Assignment_Datasets/train_dataset")

import json

with open(label_path) as f:
    labels = json.load(f)

print(type(labels))
print(len(labels))

sample = list(labels.keys())[0]

print(sample)
print(labels[sample])

from collections import Counter
shapes = []
for key in labels:
    if "verified_shape" in labels[key]:
        shapes.append(labels[key]["verified_shape"])
print(Counter(shapes))

xs = []
ys = []

for key in labels:
    xs.append(labels[key]["mark"]["x"])
    ys.append(labels[key]["mark"]["y"])

print("Min X:", min(xs))
print("Max X:", max(xs))

print("Min Y:", min(ys))
print("Max Y:", max(ys))

img_path = train_path + "/" + sample

print(img_path)
print(os.path.exists(img_path))

img = cv2.imread(img_path)

print("Loaded:", img is not None)

print(sample)

dataset_path = "/content/drive/MyDrive/GCP_Assignment_Datasets"
train_path = dataset_path + "/train_dataset"
test_path = dataset_path + "/test_dataset"

img_path = train_path + "/" + sample

print(img_path)
print(os.path.exists(img_path))

img = cv2.imread(img_path)

if img is None:
    print("Image failed to load")
else:
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
plt.title("Sample Image")
plt.show()

x = labels[sample]["mark"]["x"]
y = labels[sample]["mark"]["y"]

cv2.circle(img,(int(x),int(y)),40,(255,0,0),5)

plt.imshow(img)
plt.title("GCP Marker Center")
plt.show()

x = labels[sample]["mark"]["x"]
y = labels[sample]["mark"]["y"]

cv2.circle(img,(int(x),int(y)),40,(255,0,0),5)

plt.imshow(img)
plt.title("GCP Marker Center")
plt.show()

shape_map = {
    "Cross": 0,
    "Square": 1,
    "L-Shape": 2
}

reverse_map = {v: k for k, v in shape_map.items()}

import torch
import torchvision.transforms as transforms
import torchvision.models as models
import torch.nn as nn

from torch.utils.data import Dataset, DataLoader

transform = transforms.Compose([
    transforms.ToPILImage(),
    transforms.Resize((224,224)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor()
])

class GCPDataset(Dataset):

    def __init__(self, root, labels, transform=None):
        self.root = root
        self.labels = labels
        self.paths = list(labels.keys())
        self.transform = transform

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):

        path = self.paths[idx]

        img = cv2.imread(self.root + "/" + path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        h, w, _ = img.shape

        label = self.labels[path]

        x = label["mark"]["x"]
        y = label["mark"]["y"]

        # scale coordinates for resized image
        x = x * 224 / w
        y = y * 224 / h

        shape = shape_map[label["verified_shape"]]

        img = cv2.resize(img, (224,224))

        if self.transform:
            img = self.transform(img)

        return img, torch.tensor([x,y],dtype=torch.float32), torch.tensor(shape)

dataset = GCPDataset(train_path, labels, transform)

print("Dataset size:", len(dataset))

loader = DataLoader(dataset, batch_size=8, shuffle=True)

class GCPModel(nn.Module):

    def __init__(self):

        super().__init__()

        backbone = models.resnet18(pretrained=True)

        self.features = nn.Sequential(*list(backbone.children())[:-1])

        self.fc_xy = nn.Linear(512,2)

        self.fc_shape = nn.Linear(512,3)

    def forward(self,x):

        x = self.features(x)

        x = x.view(x.size(0),-1)

        xy = self.fc_xy(x)

        shape = self.fc_shape(x)

        return xy,shape

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = GCPModel().to(device)

mse = nn.MSELoss()

ce = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

class GCPDataset(Dataset):

    def __init__(self, root, labels, transform=None):

        self.root = root
        self.transform = transform

        # keep only valid samples
        self.data = []

        for path in labels:
            if "verified_shape" in labels[path]:
                self.data.append((path, labels[path]))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        path, label = self.data[idx]

        img = cv2.imread(self.root + "/" + path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        h, w, _ = img.shape

        x = label["mark"]["x"]
        y = label["mark"]["y"]

        # scale coordinates
        x = x * 224 / w
        y = y * 224 / h

        shape = shape_map[label["verified_shape"]]

        img = cv2.resize(img, (224,224))

        if self.transform:
            img = self.transform(img)

        return img, torch.tensor([x,y],dtype=torch.float32), torch.tensor(shape)

dataset = GCPDataset(train_path, labels, transform)

print("Dataset size:", len(dataset))

loader = DataLoader(dataset, batch_size=8, shuffle=True)

loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

epochs = 3

for epoch in range(epochs):

    total_loss = 0

    for images,xy,shape in loader:

        images = images.to(device)
        xy = xy.to(device)
        shape = shape.to(device)

        pred_xy,pred_shape = model(images)

        loss_xy = mse(pred_xy,xy)
        loss_shape = ce(pred_shape,shape)

        loss = loss_xy + loss_shape

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}  Loss: {total_loss:.2f}")

torch.save(model.state_dict(), "gcp_model.pth")
print("Model saved")

import os
def get_images(folder):
    images = []
    for root, dirs, files in os.walk(folder):
        for f in files:
            if f.lower().endswith(".jpg"):
                images.append(os.path.join(root, f))
    return images
test_images = get_images(test_path)
print("Total test images:", len(test_images))

model.eval()

results = {}

for path in test_images:

    img = cv2.imread(path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    h,w,_ = img.shape

    img_resized = cv2.resize(img,(224,224))

    img_tensor = transform(img_resized).unsqueeze(0).to(device)

    xy,shape = model(img_tensor)

    shape = torch.argmax(shape).item()

x = xy[0][0].item() * w / 224
y = xy[0][1].item() * h / 224

rel_path = os.path.relpath(path,test_path)

results[rel_path] = {
    "mark":{
        "x":float(x),
        "y":float(y)
    },
    "verified_shape":reverse_map[shape]
}

import json

with open("predictions.json","w") as f:
    json.dump(results,f,indent=4)

print("predictions.json created")

import os

print(os.path.exists("predictions.json"))

import json

with open("predictions.json") as f:
    data = json.load(f)

print(len(data))

for i,(k,v) in enumerate(data.items()):
    print(k,v)
    if i==3:
        break

import random

sample_path = random.choice(list(data.keys()))

img_path = test_path + "/" + sample_path

img = cv2.imread(img_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

x = data[sample_path]["mark"]["x"]
y = data[sample_path]["mark"]["y"]

cv2.circle(img,(int(x),int(y)),40,(255,0,0),5)

plt.imshow(img)
plt.title(data[sample_path]["verified_shape"])
plt.show()

